### ISSUE TITLE
Device Calibration

### ISSUE THREAD

**Issue by alexanderkjones** [alexanderkjones/GM_V1#6]
**Story**
As a user, I want to calibrate my scale to accurately read grams, to ensure my readings or correct across all devices.

**Desc**
Each scale must be calibrated to a 500g weight at the assembly shop and may need to be recalibrated in the future. The current process includes taring the scale, adding a 500g weight to the top of the load cell, measuring the delta and dividing by 500 to define the scaler in ```scale.set_scale(43.5)```

When a user is connected to the device in configuration mode they should be able to select a navigation button called "Calibrate" at the bottom of the screen leading them to a calibration page "192.168.4.1/calibration"

The page should allow the user to temporarily zero the scale, add a calibration weight, measure the delta and map to the numerical weight of the calibration weight in grams. This should reconfigure the HX711 output using ```scale.set_scale(VALUE)```

Once the calibration is finished the user should see a success message and be routed back to the configuration screen.

```
<h1> Calibration Settings </h1>
To recalibrate your device please do the following:

1) Select this button to Zero your scale
<button type="button">Zero Scale</button>

2) Add a known weight on top of your scale

3) Enter the weight in grams of your calibration weight
Calibration Weight Value: <input type="text"><br>

4) Click Confirm
<button type="button">Calibrate and Confirm</button>
```

**Acceptance Criteria**
- User can access calibration tool during configuration
- User can tare scale temporarily, add a calibration weight and enter the weight of the calibration weight
- System calculates ADC reading delta and maps to weight in grams
- System applies calibration scaler to system
- User sees success message
- User sees error message if A) No delta recorded, B) No weight value entered, C) Non numeric value in text box entered
- User routed back to config page on success

**Comment by JLJTGR** [comment]
Success | Failure
---- | ----
![issue6-1](https://cloud.githubusercontent.com/assets/5780236/15313291/63eac38a-1bd8-11e6-98c2-6622f8ca262e.png) | -
![issue6-2](https://cloud.githubusercontent.com/assets/5780236/15313294/6bb743c2-1bd8-11e6-9029-7cb1a10a57fc.png) | ![issue6-3](https://cloud.githubusercontent.com/assets/5780236/15313296/6e8566ba-1bd8-11e6-80b1-df3fb3955dfe.png) 
![issue6-4](https://cloud.githubusercontent.com/assets/5780236/15313298/71070e20-1bd8-11e6-9829-0664caa512fc.png) | ![issue6-5](https://cloud.githubusercontent.com/assets/5780236/15313300/738fda96-1bd8-11e6-91a1-4a16dc08a14f.png)
