### ISSUE TITLE
Send batch data to Google Sheet Using Pushing Box

### ISSUE THREAD

**Issue by alexanderkjones** [alexanderkjones/GM_V1#7]
**Story**
As a user, I want to see all my pour data published to a google spreadsheet, in order to see specific pours and create my own analysis.

**Description**
For our first field test we will be storing data in google sheets and running reports within google. We have setup pushingbox.com services for each of the prospective clients. The URI below submits data to the fields of a google form that populates a google sheet for one of our clients Honey Paw Restaurant. All data should succesfully populate this sheet https://docs.google.com/spreadsheets/d/13gy51LEY5F0bnGllZ5uXBI6V6xXNfgp90p9Ko0x9In8/edit?usp=sharing

Host: api.pushingbox.com
Pushing box requires a devid which it assigns as part of the URI. For this case, Honey Paw's devid is `v8C0805331DE2F9D`
URL is comprised of the following string

```
  String url = "/pushingbox?";
  url += "devid=v8C0805331DE2F9D&";
  url += "delta=";
  url += delta;
  url += "&scaleid=";
  url +=  macAddress

```

Notes on grabbing esp original mac address
https://github.com/esp8266/Arduino/issues/313

**Previous test code**
Note: this is for a different pushingbox device id

```
//api.pushingbox.com/pushingbox?devid=vCCD635689EAA1BE&delta=1111&scaleid=11

void senddata(int delta){

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  WiFiClient client;
  const int httpPort = 80;
  if (!client.connect(host, httpPort)) {
    Serial.println("connection failed");
    return;
  }

  // We now create a URI for the request
  String url = "/pushingbox?";
  url += "devid=vCCD635689EAA1BE&";
  url += "delta=";
  url += delta;
  url += "&scaleid=22";

  Serial.print("Requesting URL: ");
  Serial.println(url);

  // This will send the request to the server
  client.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");

  delay(500);

  // Read all the lines of the reply from server and print them to Serial
  while(client.available()){
    String line = client.readStringUntil('\r');
    Serial.print(line);
  }

  Serial.println();
  Serial.println("closing connection");


  }
```

**Comment by alexanderkjones** [comment]
@JLJTGR calibration looked great. Can you send me an eta for this issue? We're shooting for a full test on Monday/Tuesday if possible.

**Comment by JLJTGR** [comment]
I figured I would have most of Saturday to look at it. It doesn't look too difficult, but nothing really does until you actually go to do it.

**Comment by JLJTGR** [comment]
In the end, this implementation won't really work.  The scales record timestamps with the intention that they will be used later... but there is no way to pass that information with this API.  Each row just uses the current time, so batch exports won't work.  The build up so far has assumed that the scale would retain data and batch export... I can modify it temporarily to batch export every "1" data sample, but for the future this needs to be reevaluated.

**Comment by JLJTGR** [comment]
As you can see by the serial output, when the scale exports its data it ends up delaying the next measurement by about 20 seconds instead of 5 seconds.  A consequence of needing to connect to the remote WiFi.  As I said above, this should only happen every so often for batches... but it can probably be streamlined a bit.
```
2016-05-22 | 00:07:11
TrackPour: -80
Sleeping for 5 seconds...

2016-05-22 | 00:07:21
Starting local AP: ESP_01560E...
Local AP IP: 192.168.4.1
Web server started...
Connecting to SSID: JLJTGR...
-
-
-
-
-
-
Connected; WAN IP: 192.168.173.100
Exporting 1 packets....
2016-05-22 00:07:13 = -80
HTTP begin... get... 200...
=======================

=======================
Done.
Disconnecting...
Sleeping for 5 seconds...

2016-05-22 | 00:07:39
```
